# Version for the build. We make it clear that it's
# Appveyor as this isn't a version we expect to make
# it elsewhere...
version: 1.0.{build}-appveyor
image: Visual Studio 2019
configuration: Release

branches:
  only:
    - master

before_build:
  - nuget restore
